on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate build & release
        run: |
          choco install zola
          zola build --output-dir docs

      - name: Publish
        run: |
          git config --global user.email "nigeleke@users.noreply.github.com"
          git config --global user.name "Nigel Eke"
          git checkout gh-pages
          cp -r ./public/* .
          git add .
          git commit -m "Release"
          git push
